name: Create and publish a Docker image

on:
#   schedule:
#       - cron:  '0 23 28 * *'
  workflow_dispatch:
  push:
    # branches:
    #   - 'main'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-*-*'

jobs:
    build:
      runs-on: ubuntu-latest
      steps:

        - name: Check Out Repo 
          uses: actions/checkout@v3

        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

        - name: Set up Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v2

        - name: Set tag env variable
          id: vars
          run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

        - name: Build and push
          id: docker_build
          uses: docker/build-push-action@v4
          with:
            context: ./
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pytorch-notebook:${{ steps.vars.outputs.tag }} , ${{ secrets.DOCKER_HUB_USERNAME }}/pytorch-notebook:latest

        - name: Image digest
          run: echo ${{ steps.docker_build.outputs.digest }}
